### ISSUE TITLE
Add flag to install script for automated installs

### ISSUE THREAD

**Issue by bluecanarybe** [Zarcolio/grepaddr#1]
I would like to add this to an installation script  for security tooling. It would be great if a flag could be given to install.sh so it doesn't ask for 2ulb to install but just does it right away.

**Comment by Zarcolio** [comment]
Thanks for using my script, hope you find it useful :)
I've added the cmdline argument -auto.
Let me know if it works for you.
May I ask what you're using GrepAddr for?

**Comment by bluecanarybe** [comment]
Great thanks!

I find it useful during pentesting to extract information without having to bother with manual regex or copy/paste it in cyberchef.
